################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
C:/Users/Maste/git/STM32CubeL5/Projects/NUCLEO-L552ZE-Q/Applications/FreeRTOS/FreeRTOS_SecureIOToggle_TrustZone/Secure/Src/main.c \
C:/Users/Maste/git/STM32CubeL5/Projects/NUCLEO-L552ZE-Q/Applications/FreeRTOS/FreeRTOS_SecureIOToggle_TrustZone/Secure/Src/secure_nsc.c \
C:/Users/Maste/git/STM32CubeL5/Projects/NUCLEO-L552ZE-Q/Applications/FreeRTOS/FreeRTOS_SecureIOToggle_TrustZone/Secure/Src/stm32l5xx_hal_msp.c \
C:/Users/Maste/git/STM32CubeL5/Projects/NUCLEO-L552ZE-Q/Applications/FreeRTOS/FreeRTOS_SecureIOToggle_TrustZone/Secure/Src/stm32l5xx_it.c \
../Application/User/syscalls.c \
../Application/User/sysmem.c 

OBJS += \
./Application/User/main.o \
./Application/User/secure_nsc.o \
./Application/User/stm32l5xx_hal_msp.o \
./Application/User/stm32l5xx_it.o \
./Application/User/syscalls.o \
./Application/User/sysmem.o 

C_DEPS += \
./Application/User/main.d \
./Application/User/secure_nsc.d \
./Application/User/stm32l5xx_hal_msp.d \
./Application/User/stm32l5xx_it.d \
./Application/User/syscalls.d \
./Application/User/sysmem.d 


# Each subdirectory must supply rules for building sources it contributes
Application/User/main.o: C:/Users/Maste/git/STM32CubeL5/Projects/NUCLEO-L552ZE-Q/Applications/FreeRTOS/FreeRTOS_SecureIOToggle_TrustZone/Secure/Src/main.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32L552xx -DDEBUG -c -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32L5xx/Include -I../../../../../../../../Drivers/STM32L5xx_HAL_Driver/Inc -I../../../Secure_nsclib -I../../../../../../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM33/non_secure -I../../../Secure/Inc -I../../../../../../../../Drivers/BSP/STM32L5xx_Nucleo -I../../../../../../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM33/secure -I../../../../../../../../Drivers/STM32L5xx_HAL_Driver/Inc/Legacy -I../../../../../../../../Drivers/CMSIS/Include -IC:/Users/Maste/STM32Cube/Repository/STM32Cube_FW_L5_V1.3.1/Drivers/STM32L5xx_HAL_Driver/Inc -IC:/Users/Maste/STM32Cube/Repository/STM32Cube_FW_L5_V1.3.1/Drivers/CMSIS/Device/ST/STM32L5xx/Include -IC:/Users/Maste/STM32Cube/Repository/STM32Cube_FW_L5_V1.3.1/Drivers/STM32L5xx_HAL_Driver/Inc/Legacy -IC:/Users/Maste/STM32Cube/Repository/STM32Cube_FW_L5_V1.3.1/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM33/secure -IC:/Users/Maste/STM32Cube/Repository/STM32Cube_FW_L5_V1.3.1/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM33/non_secure -IC:/Users/Maste/STM32Cube/Repository/STM32Cube_FW_L5_V1.3.1/Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -mcmse -MMD -MP -MF"Application/User/main.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/secure_nsc.o: C:/Users/Maste/git/STM32CubeL5/Projects/NUCLEO-L552ZE-Q/Applications/FreeRTOS/FreeRTOS_SecureIOToggle_TrustZone/Secure/Src/secure_nsc.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32L552xx -DDEBUG -c -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32L5xx/Include -I../../../../../../../../Drivers/STM32L5xx_HAL_Driver/Inc -I../../../Secure_nsclib -I../../../../../../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM33/non_secure -I../../../Secure/Inc -I../../../../../../../../Drivers/BSP/STM32L5xx_Nucleo -I../../../../../../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM33/secure -I../../../../../../../../Drivers/STM32L5xx_HAL_Driver/Inc/Legacy -I../../../../../../../../Drivers/CMSIS/Include -IC:/Users/Maste/STM32Cube/Repository/STM32Cube_FW_L5_V1.3.1/Drivers/STM32L5xx_HAL_Driver/Inc -IC:/Users/Maste/STM32Cube/Repository/STM32Cube_FW_L5_V1.3.1/Drivers/CMSIS/Device/ST/STM32L5xx/Include -IC:/Users/Maste/STM32Cube/Repository/STM32Cube_FW_L5_V1.3.1/Drivers/STM32L5xx_HAL_Driver/Inc/Legacy -IC:/Users/Maste/STM32Cube/Repository/STM32Cube_FW_L5_V1.3.1/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM33/secure -IC:/Users/Maste/STM32Cube/Repository/STM32Cube_FW_L5_V1.3.1/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM33/non_secure -IC:/Users/Maste/STM32Cube/Repository/STM32Cube_FW_L5_V1.3.1/Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -mcmse -MMD -MP -MF"Application/User/secure_nsc.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/stm32l5xx_hal_msp.o: C:/Users/Maste/git/STM32CubeL5/Projects/NUCLEO-L552ZE-Q/Applications/FreeRTOS/FreeRTOS_SecureIOToggle_TrustZone/Secure/Src/stm32l5xx_hal_msp.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32L552xx -DDEBUG -c -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32L5xx/Include -I../../../../../../../../Drivers/STM32L5xx_HAL_Driver/Inc -I../../../Secure_nsclib -I../../../../../../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM33/non_secure -I../../../Secure/Inc -I../../../../../../../../Drivers/BSP/STM32L5xx_Nucleo -I../../../../../../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM33/secure -I../../../../../../../../Drivers/STM32L5xx_HAL_Driver/Inc/Legacy -I../../../../../../../../Drivers/CMSIS/Include -IC:/Users/Maste/STM32Cube/Repository/STM32Cube_FW_L5_V1.3.1/Drivers/STM32L5xx_HAL_Driver/Inc -IC:/Users/Maste/STM32Cube/Repository/STM32Cube_FW_L5_V1.3.1/Drivers/CMSIS/Device/ST/STM32L5xx/Include -IC:/Users/Maste/STM32Cube/Repository/STM32Cube_FW_L5_V1.3.1/Drivers/STM32L5xx_HAL_Driver/Inc/Legacy -IC:/Users/Maste/STM32Cube/Repository/STM32Cube_FW_L5_V1.3.1/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM33/secure -IC:/Users/Maste/STM32Cube/Repository/STM32Cube_FW_L5_V1.3.1/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM33/non_secure -IC:/Users/Maste/STM32Cube/Repository/STM32Cube_FW_L5_V1.3.1/Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -mcmse -MMD -MP -MF"Application/User/stm32l5xx_hal_msp.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/stm32l5xx_it.o: C:/Users/Maste/git/STM32CubeL5/Projects/NUCLEO-L552ZE-Q/Applications/FreeRTOS/FreeRTOS_SecureIOToggle_TrustZone/Secure/Src/stm32l5xx_it.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32L552xx -DDEBUG -c -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32L5xx/Include -I../../../../../../../../Drivers/STM32L5xx_HAL_Driver/Inc -I../../../Secure_nsclib -I../../../../../../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM33/non_secure -I../../../Secure/Inc -I../../../../../../../../Drivers/BSP/STM32L5xx_Nucleo -I../../../../../../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM33/secure -I../../../../../../../../Drivers/STM32L5xx_HAL_Driver/Inc/Legacy -I../../../../../../../../Drivers/CMSIS/Include -IC:/Users/Maste/STM32Cube/Repository/STM32Cube_FW_L5_V1.3.1/Drivers/STM32L5xx_HAL_Driver/Inc -IC:/Users/Maste/STM32Cube/Repository/STM32Cube_FW_L5_V1.3.1/Drivers/CMSIS/Device/ST/STM32L5xx/Include -IC:/Users/Maste/STM32Cube/Repository/STM32Cube_FW_L5_V1.3.1/Drivers/STM32L5xx_HAL_Driver/Inc/Legacy -IC:/Users/Maste/STM32Cube/Repository/STM32Cube_FW_L5_V1.3.1/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM33/secure -IC:/Users/Maste/STM32Cube/Repository/STM32Cube_FW_L5_V1.3.1/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM33/non_secure -IC:/Users/Maste/STM32Cube/Repository/STM32Cube_FW_L5_V1.3.1/Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -mcmse -MMD -MP -MF"Application/User/stm32l5xx_it.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/syscalls.o: ../Application/User/syscalls.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32L552xx -DDEBUG -c -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32L5xx/Include -I../../../../../../../../Drivers/STM32L5xx_HAL_Driver/Inc -I../../../Secure_nsclib -I../../../../../../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM33/non_secure -I../../../Secure/Inc -I../../../../../../../../Drivers/BSP/STM32L5xx_Nucleo -I../../../../../../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM33/secure -I../../../../../../../../Drivers/STM32L5xx_HAL_Driver/Inc/Legacy -I../../../../../../../../Drivers/CMSIS/Include -IC:/Users/Maste/STM32Cube/Repository/STM32Cube_FW_L5_V1.3.1/Drivers/STM32L5xx_HAL_Driver/Inc -IC:/Users/Maste/STM32Cube/Repository/STM32Cube_FW_L5_V1.3.1/Drivers/CMSIS/Device/ST/STM32L5xx/Include -IC:/Users/Maste/STM32Cube/Repository/STM32Cube_FW_L5_V1.3.1/Drivers/STM32L5xx_HAL_Driver/Inc/Legacy -IC:/Users/Maste/STM32Cube/Repository/STM32Cube_FW_L5_V1.3.1/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM33/secure -IC:/Users/Maste/STM32Cube/Repository/STM32Cube_FW_L5_V1.3.1/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM33/non_secure -IC:/Users/Maste/STM32Cube/Repository/STM32Cube_FW_L5_V1.3.1/Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -mcmse -MMD -MP -MF"Application/User/syscalls.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/sysmem.o: ../Application/User/sysmem.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m33 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32L552xx -DDEBUG -c -I../../../../../../../../Drivers/CMSIS/Device/ST/STM32L5xx/Include -I../../../../../../../../Drivers/STM32L5xx_HAL_Driver/Inc -I../../../Secure_nsclib -I../../../../../../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM33/non_secure -I../../../Secure/Inc -I../../../../../../../../Drivers/BSP/STM32L5xx_Nucleo -I../../../../../../../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM33/secure -I../../../../../../../../Drivers/STM32L5xx_HAL_Driver/Inc/Legacy -I../../../../../../../../Drivers/CMSIS/Include -IC:/Users/Maste/STM32Cube/Repository/STM32Cube_FW_L5_V1.3.1/Drivers/STM32L5xx_HAL_Driver/Inc -IC:/Users/Maste/STM32Cube/Repository/STM32Cube_FW_L5_V1.3.1/Drivers/CMSIS/Device/ST/STM32L5xx/Include -IC:/Users/Maste/STM32Cube/Repository/STM32Cube_FW_L5_V1.3.1/Drivers/STM32L5xx_HAL_Driver/Inc/Legacy -IC:/Users/Maste/STM32Cube/Repository/STM32Cube_FW_L5_V1.3.1/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM33/secure -IC:/Users/Maste/STM32Cube/Repository/STM32Cube_FW_L5_V1.3.1/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM33/non_secure -IC:/Users/Maste/STM32Cube/Repository/STM32Cube_FW_L5_V1.3.1/Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -mcmse -MMD -MP -MF"Application/User/sysmem.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

